### ISSUE TITLE
Can you please make a tool that can search for a book in all the overdrive libraries?

### ISSUE THREAD

**Issue by ghost** [ping/overdrive-libraries#1]
Not a issue but you seem to know about overdrive site scraping. Overdrive and libby only shows books and libraries based on user's location (within 50 miles, i think). So, if i want to search a book that's "out of range" , I'll have to search different library sites individually. Most of the libraries offer non-resident cards which is pretty cheap ($20-$30 per year). So if you can make a tool that shows all the libraries while searching a book, it will be really helpful.

**Comment by ghost** [comment]
![Screenshot_20230624-202450](https://github.com/ping/overdrive-libraries/assets/135785643/c6b29e45-9c6b-406a-9d7e-04aef150551d)
Only shows 92 entries.

**Comment by ping** [comment]
That's not possible.

If you sign up for an account overdrive.com and link up your libraries ("saved" libraries), you can search across all your libraries' holdings.

**Comment by p1nkyy** [comment]
Hi, just to piggyback this question, how do you search efficiently to show all the holds in each of the library you've saved?

**Comment by ping** [comment]
https://libbyapp.com/shelf/holds

OverDrive has no such ability.
